# Generated by Django 4.2 on 2024-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null='True')),
                ('phone', models.CharField(max_length=10, null='True')),
                ('desc', models.TextField(null='True')),
                ('var', models.TextField(null='True')),
                ('var2', models.TextField(null='True')),
            ],
        ),
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=89)),
                ('lname', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=90)),
                ('pass1', models.CharField(max_length=90)),
                ('pass2', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80, null=True)),
                ('fname', models.CharField(max_length=89, null=True)),
                ('lname', models.CharField(max_length=88, null=True)),
                ('email', models.EmailField(max_length=90, null=True)),
                ('pass1', models.CharField(max_length=90, null=True)),
                ('pass2', models.CharField(max_length=90, null=True)),
            ],
        ),
    ]
